"""initial schema

Revision ID: 0001_initial
Revises: 
Create Date: 2026-05-26 10:29:34.985975

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0001_initial'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Extensions must exist before any CITEXT column or gin_trgm_ops index.
    # Autogenerate never emits these; mirrors the live unichat DB.
    op.execute("CREATE EXTENSION IF NOT EXISTS citext")
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm")
    op.execute("CREATE EXTENSION IF NOT EXISTS pgcrypto")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('login_attempt_log',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('ip', sa.Text(), nullable=True),
    sa.Column('email', sa.Text(), nullable=True),
    sa.Column('at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_login_attempt_at', 'login_attempt_log', ['at'], unique=False)
    op.create_index('ix_login_attempt_ip_email_at', 'login_attempt_log', ['ip', 'email', 'at'], unique=False)
    op.create_table('openrouter_models',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('display_name', sa.Text(), nullable=True),
    sa.Column('context_length', sa.Integer(), nullable=True),
    sa.Column('architecture', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=True),
    sa.Column('pricing', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=True),
    sa.Column('supported_parameters', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=True),
    sa.Column('raw', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=True),
    sa.Column('expiration_date', sa.Date(), nullable=True),
    sa.Column('last_synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_openrouter_models_expiration', 'openrouter_models', ['expiration_date'], unique=False)
    op.create_index('ix_openrouter_models_input_modalities', 'openrouter_models', [sa.literal_column("(architecture->'input_modalities')")], unique=False, postgresql_using='gin')
    op.create_index('ix_openrouter_models_last_synced', 'openrouter_models', ['last_synced_at'], unique=False)
    op.create_index('ix_openrouter_models_output_modalities', 'openrouter_models', [sa.literal_column("(architecture->'output_modalities')")], unique=False, postgresql_using='gin')
    op.create_table('prompt_templates',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('category', sa.Text(), nullable=True),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('variables', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('usage_count', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('is_seed', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', postgresql.CITEXT(), nullable=False),
    sa.Column('password_hash', sa.LargeBinary(), nullable=True),
    sa.Column('role', sa.Text(), server_default=sa.text("'user'"), nullable=False),
    sa.Column('display_name', sa.Text(), nullable=True),
    sa.Column('keycloak_sub', sa.UUID(), nullable=True),
    sa.Column('active_workspace_id', sa.UUID(), nullable=True),
    sa.Column('profile', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('settings', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('usage', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('status', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('ai_preferences', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.CheckConstraint("role IN ('user', 'manager', 'admin')", name='ck_users_role'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    # users.active_workspace_id -> workspaces.id is added after workspaces
    # exists (users <-> workspaces is a circular FK dependency).
    op.create_index('ix_users_banned', 'users', ['id'], unique=False, postgresql_where=sa.text("(status->>'is_banned')::bool = true"))
    op.create_index('ix_users_role', 'users', ['role'], unique=False)
    op.create_index('uq_users_keycloak_sub', 'users', ['keycloak_sub'], unique=True, postgresql_where=sa.text('keycloak_sub IS NOT NULL'))
    op.create_table('workspaces',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('slug', sa.Text(), nullable=False),
    sa.Column('owner_user_id', sa.UUID(), nullable=True),
    sa.Column('is_personal', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('display_name', sa.Text(), nullable=True),
    sa.Column('settings', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('ip_allowlist', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('avatar', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('credits_balance_usd', sa.Numeric(precision=14, scale=8), server_default=sa.text('0'), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['owner_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_index('ix_workspaces_owner_user_id', 'workspaces', ['owner_user_id'], unique=False)
    op.create_foreign_key('users_active_workspace_id_fkey', 'users', 'workspaces', ['active_workspace_id'], ['id'], ondelete='SET NULL')
    op.create_table('arena_sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('topic', sa.Text(), nullable=True),
    sa.Column('status', sa.Text(), nullable=True),
    sa.Column('config_ids', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('session_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('active','completed','error')", name='ck_arena_sessions_status'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_arena_sessions_config_ids', 'arena_sessions', ['config_ids'], unique=False, postgresql_using='gin', postgresql_ops={'config_ids': 'jsonb_path_ops'})
    op.create_table('audit_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('admin_user_id', sa.UUID(), nullable=True),
    sa.Column('action', sa.Text(), nullable=False),
    sa.Column('target_id', sa.Text(), nullable=True),
    sa.Column('target_type', sa.Text(), nullable=True),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['admin_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_audit_logs_action', 'audit_logs', ['action'], unique=False)
    op.create_index('ix_audit_logs_admin', 'audit_logs', ['admin_user_id'], unique=False)
    op.create_index('ix_audit_logs_created_brin', 'audit_logs', ['created_at'], unique=False, postgresql_using='brin')
    op.create_index('ix_audit_logs_target', 'audit_logs', ['target_id'], unique=False)
    op.create_table('automate_tasks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('prompt', sa.Text(), nullable=True),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('external_task_id', sa.Text(), nullable=True),
    sa.Column('result', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('pending','running','completed','failed','cancelled')", name='ck_automate_tasks_status'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_automate_tasks_user_created', 'automate_tasks', ['user_id', sa.literal_column('created_at DESC')], unique=False)
    op.create_table('credit_ledger',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('delta_micro_usd', sa.BigInteger(), nullable=False),
    sa.Column('kind', sa.Text(), nullable=False),
    sa.Column('ref', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_by_user_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("kind IN ('topup','adjustment','refund')", name='ck_credit_ledger_kind'),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_credit_ledger_workspace_created', 'credit_ledger', ['workspace_id', sa.literal_column('created_at DESC')], unique=False)
    op.create_table('debate_sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('topic', sa.Text(), nullable=True),
    sa.Column('status', sa.Text(), nullable=True),
    sa.Column('config_ids', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('settings', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('verdict', sa.Text(), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('active','completed','error')", name='ck_debate_sessions_status'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_debate_sessions_config_ids', 'debate_sessions', ['config_ids'], unique=False, postgresql_using='gin', postgresql_ops={'config_ids': 'jsonb_path_ops'})
    op.create_table('generated_audio',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('voice', sa.Text(), nullable=True),
    sa.Column('model', sa.Text(), nullable=True),
    sa.Column('url', sa.Text(), nullable=True),
    sa.Column('audio_metadata', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_generated_audio_created', 'generated_audio', [sa.literal_column('created_at DESC')], unique=False)
    op.create_index('ix_generated_audio_user', 'generated_audio', ['user_id'], unique=False)
    op.create_table('generated_images',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('prompt', sa.Text(), nullable=True),
    sa.Column('model', sa.Text(), nullable=True),
    sa.Column('url', sa.Text(), nullable=True),
    sa.Column('b64_payload', sa.Text(), nullable=True),
    sa.Column('image_metadata', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=True),
    sa.Column('settings', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_generated_images_created', 'generated_images', [sa.literal_column('created_at DESC')], unique=False)
    op.create_index('ix_generated_images_user', 'generated_images', ['user_id'], unique=False)
    op.create_table('generated_videos',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('prompt', sa.Text(), nullable=True),
    sa.Column('model', sa.Text(), nullable=True),
    sa.Column('url', sa.Text(), nullable=True),
    sa.Column('video_metadata', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_generated_videos_created', 'generated_videos', [sa.literal_column('created_at DESC')], unique=False)
    op.create_index('ix_generated_videos_user', 'generated_videos', ['user_id'], unique=False)
    op.create_table('groups',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workspace_id', 'name', name='uq_groups_ws_name')
    )
    op.create_index('ix_groups_workspace', 'groups', ['workspace_id'], unique=False)
    op.create_table('helper_conversations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('context', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('last_message_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', name='uq_helper_conversations_user')
    )
    op.create_table('meeting_series',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('owner_user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('email_tone_preference', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['owner_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('owner_user_id', 'name', name='uq_meeting_series_owner_name')
    )
    op.create_index('ix_meeting_series_owner_updated', 'meeting_series', ['owner_user_id', sa.literal_column('updated_at DESC')], unique=False)
    op.create_table('platform_admins',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('email', postgresql.CITEXT(), nullable=False),
    sa.Column('display_name', sa.Text(), nullable=True),
    sa.Column('permissions', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('platform_settings',
    sa.Column('key', sa.Text(), nullable=False),
    sa.Column('value', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_by_user_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['updated_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('projects',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('slug', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('owner_user_id', sa.UUID(), nullable=True),
    sa.Column('archived', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('settings', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['owner_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workspace_id', 'slug', name='uq_projects_ws_slug')
    )
    op.create_index('ix_projects_ws_archived', 'projects', ['workspace_id', 'archived'], unique=False)
    op.create_table('revoked_tokens',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('jti', sa.Text(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('jti', name='uq_revoked_tokens_jti')
    )
    op.create_index('ix_revoked_tokens_created', 'revoked_tokens', ['created_at'], unique=False)
    op.create_table('stream_generation_state',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.Text(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('cancelled', sa.Boolean(), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id', name='uq_stream_state_session_id')
    )
    op.create_index('ix_stream_state_expires', 'stream_generation_state', ['expires_at'], unique=False)
    op.create_table('uploads',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('filename', sa.Text(), nullable=False),
    sa.Column('original_name', sa.Text(), nullable=True),
    sa.Column('mime_type', sa.Text(), nullable=True),
    sa.Column('size', sa.Integer(), nullable=False),
    sa.Column('type', sa.Text(), nullable=False),
    sa.Column('thumbnail_filename', sa.Text(), nullable=True),
    sa.Column('force_attachment', sa.Boolean(), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_uploads_user_created', 'uploads', ['user_id', 'created_at'], unique=False)
    op.create_table('workspace_invites',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('email', postgresql.CITEXT(), nullable=False),
    sa.Column('role', sa.Text(), nullable=False),
    sa.Column('token', sa.Text(), nullable=False),
    sa.Column('invited_by_user_id', sa.UUID(), nullable=True),
    sa.Column('expires_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('accepted_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("role IN ('owner', 'editor', 'viewer')", name='ck_workspace_invites_role'),
    sa.ForeignKeyConstraint(['invited_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token')
    )
    op.create_index('uq_workspace_invites_pending', 'workspace_invites', ['workspace_id', 'email'], unique=True, postgresql_where=sa.text('accepted_at IS NULL'))
    op.create_table('workspace_members',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.Text(), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('invited_by_user_id', sa.UUID(), nullable=True),
    sa.Column('joined_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("role IN ('owner', 'editor', 'viewer')", name='ck_workspace_members_role'),
    sa.CheckConstraint("status IN ('active', 'pending', 'removed')", name='ck_workspace_members_status'),
    sa.ForeignKeyConstraint(['invited_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workspace_id', 'user_id', name='uq_workspace_members_ws_user')
    )
    op.create_index('ix_workspace_members_user_status', 'workspace_members', ['user_id', 'status'], unique=False)
    op.create_table('arena_messages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('config_id', sa.Text(), nullable=True),
    sa.Column('role', sa.Text(), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('message_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('order_idx', sa.Integer(), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("role IN ('user','assistant','system','tool')", name='ck_arena_messages_role'),
    sa.ForeignKeyConstraint(['session_id'], ['arena_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('automate_messages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('task_id', sa.UUID(), nullable=False),
    sa.Column('cursor_id', sa.Text(), nullable=False),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['automate_tasks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('task_id', 'cursor_id', name='uq_automate_messages_task_cursor')
    )
    op.create_table('debate_messages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('config_id', sa.Text(), nullable=True),
    sa.Column('role', sa.Text(), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('message_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('order_idx', sa.Integer(), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("role IN ('user','assistant','system','tool')", name='ck_debate_messages_role'),
    sa.ForeignKeyConstraint(['session_id'], ['debate_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dlp_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('workspace_id', sa.UUID(), nullable=True),
    sa.Column('project_id', sa.UUID(), nullable=True),
    sa.Column('source', sa.Text(), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('highest_action', sa.Text(), nullable=False),
    sa.Column('highest_severity', sa.Text(), nullable=False),
    sa.Column('text_sha256', sa.Text(), nullable=False),
    sa.Column('source_ref', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("highest_action IN ('block','require_confirm','warn','allow')", name='ck_dlp_events_highest_action'),
    sa.CheckConstraint("highest_severity IN ('critical','high','medium','low','none')", name='ck_dlp_events_highest_severity'),
    sa.CheckConstraint("source IN ('chat','arena','workflow','helper','image_prompt','meeting','debate','automate')", name='ck_dlp_events_source'),
    sa.CheckConstraint("status IN ('blocked','confirmed','warned','allowed')", name='ck_dlp_events_status'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_dlp_events_action_created', 'dlp_events', ['highest_action', sa.literal_column('created_at DESC')], unique=False)
    op.create_index('ix_dlp_events_source_ref_conv', 'dlp_events', [sa.literal_column("(source_ref->>'conversation_id')")], unique=False, postgresql_where=sa.text("source_ref ? 'conversation_id'"))
    op.create_index('ix_dlp_events_source_ref_run', 'dlp_events', [sa.literal_column("(source_ref->>'run_id')")], unique=False, postgresql_where=sa.text("source_ref ? 'run_id'"))
    op.create_index('ix_dlp_events_source_ref_workflow', 'dlp_events', [sa.literal_column("(source_ref->>'workflow_id')")], unique=False, postgresql_where=sa.text("source_ref ? 'workflow_id'"))
    op.create_index('ix_dlp_events_user_created', 'dlp_events', ['user_id', sa.literal_column('created_at DESC')], unique=False)
    op.create_index('ix_dlp_events_workspace_created', 'dlp_events', ['workspace_id', sa.literal_column('created_at DESC')], unique=False)
    op.create_index('ix_dlp_events_workspace_status_created', 'dlp_events', ['workspace_id', 'status', sa.literal_column('created_at DESC')], unique=False)
    op.create_table('folders',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('parent_id', sa.UUID(), nullable=True),
    sa.Column('position', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['folders.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_folders_user_parent', 'folders', ['user_id', 'parent_id'], unique=False)
    op.create_index('ix_folders_user_position', 'folders', ['user_id', 'position'], unique=False)
    op.create_index('ix_folders_user_project_parent', 'folders', ['user_id', 'project_id', 'parent_id'], unique=False)
    op.create_table('group_members',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('group_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('group_id', 'user_id', name='uq_group_members_group_user')
    )
    op.create_index('ix_group_members_user', 'group_members', ['user_id'], unique=False)
    op.create_table('helper_messages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('helper_conversation_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.Text(), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('order_idx', sa.BigInteger(), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("role IN ('user','assistant','system')", name='ck_helper_messages_role'),
    sa.ForeignKeyConstraint(['helper_conversation_id'], ['helper_conversations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('helper_conversation_id', 'order_idx', name='uq_helper_messages_conv_order')
    )
    op.create_table('knowledge_folders',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('workspace_id', sa.UUID(), nullable=True),
    sa.Column('project_id', sa.UUID(), nullable=True),
    sa.Column('parent_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('scope_key', sa.Text(), nullable=False),
    sa.Column('position', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['knowledge_folders.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('scope_key', 'name', name='uq_knowledge_folders_scope_name')
    )
    op.create_index('ix_knowledge_folders_project_position', 'knowledge_folders', ['project_id', 'position'], unique=False)
    op.create_index('ix_knowledge_folders_user_position', 'knowledge_folders', ['user_id', 'position'], unique=False)
    op.create_table('llm_configs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('owner_user_id', sa.UUID(), nullable=True),
    sa.Column('workspace_id', sa.UUID(), nullable=True),
    sa.Column('project_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('provider', sa.Text(), nullable=False),
    sa.Column('model', sa.Text(), nullable=False),
    sa.Column('system_prompt', sa.Text(), nullable=True),
    sa.Column('parameters', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('avatar', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('stats', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('visibility', sa.Text(), server_default=sa.text("'private'"), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("visibility IN ('private','public','template','project')", name='ck_llm_configs_visibility'),
    sa.ForeignKeyConstraint(['owner_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_llm_configs_description_trgm', 'llm_configs', ['description'], unique=False, postgresql_using='gin', postgresql_ops={'description': 'gin_trgm_ops'})
    op.create_index('ix_llm_configs_name_trgm', 'llm_configs', ['name'], unique=False, postgresql_using='gin', postgresql_ops={'name': 'gin_trgm_ops'})
    op.create_index('ix_llm_configs_owner', 'llm_configs', ['owner_user_id'], unique=False)
    op.create_index('ix_llm_configs_project_created', 'llm_configs', ['project_id', sa.literal_column('created_at DESC')], unique=False)
    op.create_index('ix_llm_configs_visibility', 'llm_configs', ['visibility'], unique=False)
    op.create_table('meeting_series_keyterms',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('series_id', sa.UUID(), nullable=False),
    sa.Column('term', sa.Text(), nullable=False),
    sa.Column('source', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("source IN ('manual','suggested','accepted')", name='ck_meeting_series_keyterm_source'),
    sa.CheckConstraint('length(term) <= 50', name='ck_meeting_series_keyterm_len'),
    sa.ForeignKeyConstraint(['series_id'], ['meeting_series.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('series_id', 'term', name='uq_meeting_series_keyterm')
    )
    op.create_index('ix_meeting_series_keyterm_series_source', 'meeting_series_keyterms', ['series_id', 'source'], unique=False)
    op.create_table('meeting_series_speaker_names',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('series_id', sa.UUID(), nullable=False),
    sa.Column('display_name', sa.Text(), nullable=False),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['series_id'], ['meeting_series.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('series_id', 'display_name', name='uq_meeting_series_speaker_name')
    )
    op.create_index('ix_meeting_series_speaker_last_used', 'meeting_series_speaker_names', ['series_id', sa.literal_column('last_used_at DESC NULLS LAST')], unique=False)
    op.create_table('meetings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('owner_user_id', sa.UUID(), nullable=False),
    sa.Column('series_id', sa.UUID(), nullable=True),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('audio_path', sa.Text(), nullable=True),
    sa.Column('audio_url', sa.Text(), nullable=True),
    sa.Column('duration_s', sa.Integer(), nullable=True),
    sa.Column('transcript_language', sa.Text(), nullable=True),
    sa.Column('email_tone', sa.Text(), nullable=True),
    sa.Column('cancel_requested', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("email_tone IS NULL OR email_tone IN ('formal', 'casual')", name='ck_meetings_email_tone'),
    sa.CheckConstraint("status IN ('uploaded', 'transcribing', 'summarizing', 'done', 'failed', 'cancelled')", name='ck_meetings_status'),
    sa.ForeignKeyConstraint(['owner_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['series_id'], ['meeting_series.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_meetings_owner_created', 'meetings', ['owner_user_id', sa.literal_column('created_at DESC')], unique=False)
    op.create_index('ix_meetings_owner_series', 'meetings', ['owner_user_id', 'series_id'], unique=False)
    op.create_index('ix_meetings_owner_status', 'meetings', ['owner_user_id', 'status'], unique=False)
    op.create_index('ix_meetings_title_trgm', 'meetings', ['title'], unique=False, postgresql_using='gin', postgresql_ops={'title': 'gin_trgm_ops'})
    op.create_table('platform_audit_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('platform_admin_id', sa.UUID(), nullable=False),
    sa.Column('action', sa.Text(), nullable=False),
    sa.Column('target_type', sa.Text(), nullable=True),
    sa.Column('target_id', sa.Text(), nullable=True),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['platform_admin_id'], ['platform_admins.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_platform_audit_logs_action', 'platform_audit_logs', ['action'], unique=False)
    op.create_index('ix_platform_audit_logs_admin', 'platform_audit_logs', ['platform_admin_id'], unique=False)
    op.create_index('ix_platform_audit_logs_created_brin', 'platform_audit_logs', ['created_at'], unique=False, postgresql_using='brin')
    op.create_table('project_group_access',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('group_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.Text(), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("role IN ('owner', 'editor', 'viewer')", name='ck_project_group_access_role'),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'group_id', name='uq_project_group_access_project_group')
    )
    op.create_table('project_members',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.Text(), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("role IN ('owner', 'editor', 'viewer')", name='ck_project_members_role'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'user_id', name='uq_project_members_project_user')
    )
    op.create_index('ix_project_members_user', 'project_members', ['user_id'], unique=False)
    op.create_table('project_webhooks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('events', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('secret_hash', sa.LargeBinary(), nullable=True),
    sa.Column('enabled', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_project_webhooks_project_created', 'project_webhooks', ['project_id', sa.literal_column('created_at DESC')], unique=False)
    op.create_table('usage_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('workspace_id', sa.UUID(), nullable=True),
    sa.Column('project_id', sa.UUID(), nullable=True),
    sa.Column('model', sa.Text(), nullable=False),
    sa.Column('provider', sa.Text(), nullable=True),
    sa.Column('origin', sa.Text(), nullable=True),
    sa.Column('feature', sa.Text(), nullable=True),
    sa.Column('input_tokens', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('output_tokens', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('cached_tokens', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('reasoning_tokens', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('image_tokens', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('web_search_tokens', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('total_tokens', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('cost_usd', sa.Numeric(precision=14, scale=8), server_default=sa.text('0'), nullable=False),
    sa.Column('tokens', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('response_usage', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('generation_id', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_usage_logs_created_brin', 'usage_logs', ['created_at'], unique=False, postgresql_using='brin')
    op.create_index('ix_usage_logs_gen_id_partial', 'usage_logs', ['generation_id'], unique=True, postgresql_where=sa.text('generation_id IS NOT NULL'))
    op.create_index('ix_usage_logs_model', 'usage_logs', ['model'], unique=False)
    op.create_index('ix_usage_logs_model_created', 'usage_logs', ['model', sa.literal_column('created_at DESC')], unique=False)
    op.create_index('ix_usage_logs_project_created', 'usage_logs', ['project_id', sa.literal_column('created_at DESC')], unique=False)
    op.create_index('ix_usage_logs_user_created', 'usage_logs', ['user_id', sa.literal_column('created_at DESC')], unique=False)
    op.create_index('ix_usage_logs_workspace_created', 'usage_logs', ['workspace_id', sa.literal_column('created_at DESC')], unique=False)
    op.create_table('workflows',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=True),
    sa.Column('project_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('nodes', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('edges', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('is_template', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('category', sa.Text(), nullable=True),
    sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('visibility', sa.Text(), server_default=sa.text("'private'"), nullable=False),
    sa.Column('version', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("visibility IN ('private','public','template','project')", name='ck_workflows_visibility'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_workflows_category', 'workflows', ['category'], unique=False)
    op.create_index('ix_workflows_is_template', 'workflows', ['is_template'], unique=False)
    op.create_index('ix_workflows_project_updated', 'workflows', ['project_id', sa.literal_column('updated_at DESC')], unique=False)
    op.create_index('ix_workflows_user_updated', 'workflows', ['user_id', sa.literal_column('updated_at DESC')], unique=False)
    op.create_table('conversations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=True),
    sa.Column('folder_id', sa.UUID(), nullable=True),
    sa.Column('config_id', sa.Text(), nullable=True),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('message_count', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('token_count', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('last_message_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('is_pinned', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('is_archived', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('active_branch', sa.Text(), server_default=sa.text("'main'"), nullable=False),
    sa.Column('seq_counter', sa.BigInteger(), server_default=sa.text('0'), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['folder_id'], ['folders.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_conversations_title_trgm', 'conversations', ['title'], unique=False, postgresql_using='gin', postgresql_ops={'title': 'gin_trgm_ops'})
    op.create_index('ix_conversations_user_archived', 'conversations', ['user_id', 'is_archived'], unique=False)
    op.create_index('ix_conversations_user_folder', 'conversations', ['user_id', 'folder_id'], unique=False)
    op.create_index('ix_conversations_user_last_message_at', 'conversations', ['user_id', sa.literal_column('last_message_at DESC NULLS LAST')], unique=False)
    op.create_index('ix_conversations_user_project_last_message_at', 'conversations', ['user_id', 'project_id', sa.literal_column('last_message_at DESC NULLS LAST')], unique=False)
    op.create_table('dlp_event_matches',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('event_id', sa.UUID(), nullable=False),
    sa.Column('rule_id', sa.Text(), nullable=False),
    sa.Column('category', sa.Text(), nullable=True),
    sa.Column('severity', sa.Text(), nullable=False),
    sa.Column('action', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('source_type', sa.Text(), nullable=False),
    sa.Column('span_start', sa.Integer(), nullable=True),
    sa.Column('span_end', sa.Integer(), nullable=True),
    sa.Column('excerpt_masked', sa.Text(), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("action IN ('block','require_confirm','warn','allow')", name='ck_dlp_event_matches_action'),
    sa.CheckConstraint("severity IN ('critical','high','medium','low','none')", name='ck_dlp_event_matches_severity'),
    sa.CheckConstraint("source_type IN ('builtin','custom','hostname','llm')", name='ck_dlp_event_matches_source_type'),
    sa.ForeignKeyConstraint(['event_id'], ['dlp_events.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('knowledge_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=True),
    sa.Column('project_id', sa.UUID(), nullable=True),
    sa.Column('folder_id', sa.UUID(), nullable=True),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('source_type', sa.Text(), nullable=True),
    sa.Column('source_id', sa.Text(), nullable=True),
    sa.Column('source_ref', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('message_id', sa.Text(), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['folder_id'], ['knowledge_folders.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_knowledge_items_content_trgm', 'knowledge_items', ['content'], unique=False, postgresql_using='gin', postgresql_ops={'content': 'gin_trgm_ops'})
    op.create_index('ix_knowledge_items_notes_trgm', 'knowledge_items', ['notes'], unique=False, postgresql_using='gin', postgresql_ops={'notes': 'gin_trgm_ops'})
    op.create_index('ix_knowledge_items_project_created', 'knowledge_items', ['project_id', sa.literal_column('created_at DESC')], unique=False)
    op.create_index('ix_knowledge_items_tags_gin', 'knowledge_items', ['tags'], unique=False, postgresql_using='gin', postgresql_ops={'tags': 'jsonb_path_ops'})
    op.create_index('ix_knowledge_items_title_trgm', 'knowledge_items', ['title'], unique=False, postgresql_using='gin', postgresql_ops={'title': 'gin_trgm_ops'})
    op.create_index('ix_knowledge_items_user_created', 'knowledge_items', ['user_id', sa.literal_column('created_at DESC')], unique=False)
    op.create_index('ix_knowledge_items_user_folder_created', 'knowledge_items', ['user_id', 'folder_id', sa.literal_column('created_at DESC')], unique=False)
    op.create_table('meeting_speakers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('meeting_id', sa.UUID(), nullable=False),
    sa.Column('speaker_label', sa.Text(), nullable=False),
    sa.Column('display_name', sa.Text(), nullable=True),
    sa.Column('order_idx', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['meeting_id'], ['meetings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('meeting_id', 'speaker_label', name='uq_meeting_speaker_label')
    )
    op.create_table('meeting_summaries',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('meeting_id', sa.UUID(), nullable=False),
    sa.Column('exec_summary', sa.Text(), nullable=True),
    sa.Column('email_draft', sa.Text(), nullable=True),
    sa.Column('action_items', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('decisions', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('qa', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('open_questions', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('minutes', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('speaker_names', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('model_used', sa.Text(), nullable=True),
    sa.Column('tone', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("tone IS NULL OR tone IN ('formal','casual')", name='ck_meeting_summaries_tone'),
    sa.ForeignKeyConstraint(['meeting_id'], ['meetings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_meeting_summaries_meeting_created', 'meeting_summaries', ['meeting_id', sa.literal_column('created_at DESC')], unique=False)
    op.create_table('meeting_transcripts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('meeting_id', sa.UUID(), nullable=False),
    sa.Column('raw_text', sa.Text(), nullable=True),
    sa.Column('raw_json', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=True),
    sa.Column('words_json', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=True),
    sa.Column('language_code', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['meeting_id'], ['meetings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('meeting_id', name='uq_meeting_transcripts_meeting_id')
    )
    op.create_table('workflow_runs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workflow_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('execution_mode', sa.Text(), nullable=False),
    sa.Column('start_node_id', sa.Text(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('started_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('completed_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("execution_mode IN ('full','single','from')", name='ck_workflow_runs_execution_mode'),
    sa.CheckConstraint("status IN ('pending','running','completed','failed','cancelled')", name='ck_workflow_runs_status'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workflow_id'], ['workflows.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_workflow_runs_workflow_started', 'workflow_runs', ['workflow_id', sa.literal_column('started_at DESC NULLS LAST')], unique=False)
    op.create_table('conversation_branches',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('conversation_id', sa.UUID(), nullable=False),
    sa.Column('branch_key', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('parent_branch_key', sa.Text(), nullable=True),
    sa.Column('branch_point_message_id', sa.UUID(), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('conversation_id', 'branch_key', name='uq_conversation_branches_conv_key')
    )
    op.create_table('messages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('conversation_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.Text(), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('attachments', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('message_metadata', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('branch_id', sa.Text(), server_default=sa.text("'main'"), nullable=False),
    sa.Column('is_error', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('seq', sa.BigInteger(), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("role IN ('user','assistant','system','tool')", name='ck_messages_role'),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('conversation_id', 'seq', name='uq_messages_conv_seq')
    )
    op.create_index('ix_messages_content_trgm', 'messages', ['content'], unique=False, postgresql_using='gin', postgresql_ops={'content': 'gin_trgm_ops'})
    op.create_index('ix_messages_conv_branch_created', 'messages', ['conversation_id', 'branch_id', 'created_at'], unique=False)
    op.create_index('ix_messages_conv_created_seq', 'messages', ['conversation_id', 'created_at', 'seq'], unique=False)
    op.create_table('workflow_run_node_results',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('run_id', sa.UUID(), nullable=False),
    sa.Column('node_id', sa.Text(), nullable=False),
    sa.Column('order_idx', sa.Integer(), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('output', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('started_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('completed_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.CheckConstraint("status IN ('pending','running','completed','failed','skipped')", name='ck_workflow_run_node_results_status'),
    sa.ForeignKeyConstraint(['run_id'], ['workflow_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_workflow_run_node_results_run_order', 'workflow_run_node_results', ['run_id', 'order_idx'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # Break the users <-> workspaces circular FK before dropping tables.
    op.drop_constraint('users_active_workspace_id_fkey', 'users', type_='foreignkey')
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_workflow_run_node_results_run_order', table_name='workflow_run_node_results')
    op.drop_table('workflow_run_node_results')
    op.drop_index('ix_messages_conv_created_seq', table_name='messages')
    op.drop_index('ix_messages_conv_branch_created', table_name='messages')
    op.drop_index('ix_messages_content_trgm', table_name='messages', postgresql_using='gin', postgresql_ops={'content': 'gin_trgm_ops'})
    op.drop_table('messages')
    op.drop_table('conversation_branches')
    op.drop_index('ix_workflow_runs_workflow_started', table_name='workflow_runs')
    op.drop_table('workflow_runs')
    op.drop_table('meeting_transcripts')
    op.drop_index('ix_meeting_summaries_meeting_created', table_name='meeting_summaries')
    op.drop_table('meeting_summaries')
    op.drop_table('meeting_speakers')
    op.drop_index('ix_knowledge_items_user_folder_created', table_name='knowledge_items')
    op.drop_index('ix_knowledge_items_user_created', table_name='knowledge_items')
    op.drop_index('ix_knowledge_items_title_trgm', table_name='knowledge_items', postgresql_using='gin', postgresql_ops={'title': 'gin_trgm_ops'})
    op.drop_index('ix_knowledge_items_tags_gin', table_name='knowledge_items', postgresql_using='gin', postgresql_ops={'tags': 'jsonb_path_ops'})
    op.drop_index('ix_knowledge_items_project_created', table_name='knowledge_items')
    op.drop_index('ix_knowledge_items_notes_trgm', table_name='knowledge_items', postgresql_using='gin', postgresql_ops={'notes': 'gin_trgm_ops'})
    op.drop_index('ix_knowledge_items_content_trgm', table_name='knowledge_items', postgresql_using='gin', postgresql_ops={'content': 'gin_trgm_ops'})
    op.drop_table('knowledge_items')
    op.drop_table('dlp_event_matches')
    op.drop_index('ix_conversations_user_project_last_message_at', table_name='conversations')
    op.drop_index('ix_conversations_user_last_message_at', table_name='conversations')
    op.drop_index('ix_conversations_user_folder', table_name='conversations')
    op.drop_index('ix_conversations_user_archived', table_name='conversations')
    op.drop_index('ix_conversations_title_trgm', table_name='conversations', postgresql_using='gin', postgresql_ops={'title': 'gin_trgm_ops'})
    op.drop_table('conversations')
    op.drop_index('ix_workflows_user_updated', table_name='workflows')
    op.drop_index('ix_workflows_project_updated', table_name='workflows')
    op.drop_index('ix_workflows_is_template', table_name='workflows')
    op.drop_index('ix_workflows_category', table_name='workflows')
    op.drop_table('workflows')
    op.drop_index('ix_usage_logs_workspace_created', table_name='usage_logs')
    op.drop_index('ix_usage_logs_user_created', table_name='usage_logs')
    op.drop_index('ix_usage_logs_project_created', table_name='usage_logs')
    op.drop_index('ix_usage_logs_model_created', table_name='usage_logs')
    op.drop_index('ix_usage_logs_model', table_name='usage_logs')
    op.drop_index('ix_usage_logs_gen_id_partial', table_name='usage_logs', postgresql_where=sa.text('generation_id IS NOT NULL'))
    op.drop_index('ix_usage_logs_created_brin', table_name='usage_logs', postgresql_using='brin')
    op.drop_table('usage_logs')
    op.drop_index('ix_project_webhooks_project_created', table_name='project_webhooks')
    op.drop_table('project_webhooks')
    op.drop_index('ix_project_members_user', table_name='project_members')
    op.drop_table('project_members')
    op.drop_table('project_group_access')
    op.drop_index('ix_platform_audit_logs_created_brin', table_name='platform_audit_logs', postgresql_using='brin')
    op.drop_index('ix_platform_audit_logs_admin', table_name='platform_audit_logs')
    op.drop_index('ix_platform_audit_logs_action', table_name='platform_audit_logs')
    op.drop_table('platform_audit_logs')
    op.drop_index('ix_meetings_title_trgm', table_name='meetings', postgresql_using='gin', postgresql_ops={'title': 'gin_trgm_ops'})
    op.drop_index('ix_meetings_owner_status', table_name='meetings')
    op.drop_index('ix_meetings_owner_series', table_name='meetings')
    op.drop_index('ix_meetings_owner_created', table_name='meetings')
    op.drop_table('meetings')
    op.drop_index('ix_meeting_series_speaker_last_used', table_name='meeting_series_speaker_names')
    op.drop_table('meeting_series_speaker_names')
    op.drop_index('ix_meeting_series_keyterm_series_source', table_name='meeting_series_keyterms')
    op.drop_table('meeting_series_keyterms')
    op.drop_index('ix_llm_configs_visibility', table_name='llm_configs')
    op.drop_index('ix_llm_configs_project_created', table_name='llm_configs')
    op.drop_index('ix_llm_configs_owner', table_name='llm_configs')
    op.drop_index('ix_llm_configs_name_trgm', table_name='llm_configs', postgresql_using='gin', postgresql_ops={'name': 'gin_trgm_ops'})
    op.drop_index('ix_llm_configs_description_trgm', table_name='llm_configs', postgresql_using='gin', postgresql_ops={'description': 'gin_trgm_ops'})
    op.drop_table('llm_configs')
    op.drop_index('ix_knowledge_folders_user_position', table_name='knowledge_folders')
    op.drop_index('ix_knowledge_folders_project_position', table_name='knowledge_folders')
    op.drop_table('knowledge_folders')
    op.drop_table('helper_messages')
    op.drop_index('ix_group_members_user', table_name='group_members')
    op.drop_table('group_members')
    op.drop_index('ix_folders_user_project_parent', table_name='folders')
    op.drop_index('ix_folders_user_position', table_name='folders')
    op.drop_index('ix_folders_user_parent', table_name='folders')
    op.drop_table('folders')
    op.drop_index('ix_dlp_events_workspace_status_created', table_name='dlp_events')
    op.drop_index('ix_dlp_events_workspace_created', table_name='dlp_events')
    op.drop_index('ix_dlp_events_user_created', table_name='dlp_events')
    op.drop_index('ix_dlp_events_source_ref_workflow', table_name='dlp_events', postgresql_where=sa.text("source_ref ? 'workflow_id'"))
    op.drop_index('ix_dlp_events_source_ref_run', table_name='dlp_events', postgresql_where=sa.text("source_ref ? 'run_id'"))
    op.drop_index('ix_dlp_events_source_ref_conv', table_name='dlp_events', postgresql_where=sa.text("source_ref ? 'conversation_id'"))
    op.drop_index('ix_dlp_events_action_created', table_name='dlp_events')
    op.drop_table('dlp_events')
    op.drop_table('debate_messages')
    op.drop_table('automate_messages')
    op.drop_table('arena_messages')
    op.drop_index('ix_workspace_members_user_status', table_name='workspace_members')
    op.drop_table('workspace_members')
    op.drop_index('uq_workspace_invites_pending', table_name='workspace_invites', postgresql_where=sa.text('accepted_at IS NULL'))
    op.drop_table('workspace_invites')
    op.drop_index('ix_uploads_user_created', table_name='uploads')
    op.drop_table('uploads')
    op.drop_index('ix_stream_state_expires', table_name='stream_generation_state')
    op.drop_table('stream_generation_state')
    op.drop_index('ix_revoked_tokens_created', table_name='revoked_tokens')
    op.drop_table('revoked_tokens')
    op.drop_index('ix_projects_ws_archived', table_name='projects')
    op.drop_table('projects')
    op.drop_table('platform_settings')
    op.drop_table('platform_admins')
    op.drop_index('ix_meeting_series_owner_updated', table_name='meeting_series')
    op.drop_table('meeting_series')
    op.drop_table('helper_conversations')
    op.drop_index('ix_groups_workspace', table_name='groups')
    op.drop_table('groups')
    op.drop_index('ix_generated_videos_user', table_name='generated_videos')
    op.drop_index('ix_generated_videos_created', table_name='generated_videos')
    op.drop_table('generated_videos')
    op.drop_index('ix_generated_images_user', table_name='generated_images')
    op.drop_index('ix_generated_images_created', table_name='generated_images')
    op.drop_table('generated_images')
    op.drop_index('ix_generated_audio_user', table_name='generated_audio')
    op.drop_index('ix_generated_audio_created', table_name='generated_audio')
    op.drop_table('generated_audio')
    op.drop_index('ix_debate_sessions_config_ids', table_name='debate_sessions', postgresql_using='gin', postgresql_ops={'config_ids': 'jsonb_path_ops'})
    op.drop_table('debate_sessions')
    op.drop_index('ix_credit_ledger_workspace_created', table_name='credit_ledger')
    op.drop_table('credit_ledger')
    op.drop_index('ix_automate_tasks_user_created', table_name='automate_tasks')
    op.drop_table('automate_tasks')
    op.drop_index('ix_audit_logs_target', table_name='audit_logs')
    op.drop_index('ix_audit_logs_created_brin', table_name='audit_logs', postgresql_using='brin')
    op.drop_index('ix_audit_logs_admin', table_name='audit_logs')
    op.drop_index('ix_audit_logs_action', table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index('ix_arena_sessions_config_ids', table_name='arena_sessions', postgresql_using='gin', postgresql_ops={'config_ids': 'jsonb_path_ops'})
    op.drop_table('arena_sessions')
    op.drop_index('ix_workspaces_owner_user_id', table_name='workspaces')
    op.drop_table('workspaces')
    op.drop_index('uq_users_keycloak_sub', table_name='users', postgresql_where=sa.text('keycloak_sub IS NOT NULL'))
    op.drop_index('ix_users_role', table_name='users')
    op.drop_index('ix_users_banned', table_name='users', postgresql_where=sa.text("(status->>'is_banned')::bool = true"))
    op.drop_table('users')
    op.drop_table('prompt_templates')
    op.drop_index('ix_openrouter_models_output_modalities', table_name='openrouter_models', postgresql_using='gin')
    op.drop_index('ix_openrouter_models_last_synced', table_name='openrouter_models')
    op.drop_index('ix_openrouter_models_input_modalities', table_name='openrouter_models', postgresql_using='gin')
    op.drop_index('ix_openrouter_models_expiration', table_name='openrouter_models')
    op.drop_table('openrouter_models')
    op.drop_index('ix_login_attempt_ip_email_at', table_name='login_attempt_log')
    op.drop_index('ix_login_attempt_at', table_name='login_attempt_log')
    op.drop_table('login_attempt_log')
    # ### end Alembic commands ###
